theme = "gruvbox_dark_hard"

[keys.normal]
X = "extend_line_above"
G = "goto_file_end"

[keys.normal.space]
q = ":buffer-close"

[editor]
soft-wrap.enable = true
bufferline = "multiple"
jump-label-alphabet = "tnseriaoplfuwydhc,x.q;z/"

[editor.cursor-shape]
insert = "bar"
