theme = "gruvbox_transparent"

[keys.normal]
X = "extend_line_above"
G = "goto_file_end"
W = "move_next_sub_word_start"
B = "move_prev_sub_word_start"

[keys.normal.space]
q = ":buffer-close"

[keys.select]
C-down = "shrink_selection"
C-up = "expand_selection"
C-left = "select_prev_sibling"
C-right = "select_next_sibling"

[editor]
soft-wrap.enable = true
bufferline = "multiple"
jump-label-alphabet = "tnseriaoplfuwydhc,x.q;z/"
end-of-line-diagnostics = "hint"
inline-diagnostics.cursor-line = "error"

[editor.cursor-shape]
insert = "bar"
