theme = "gruvbox_transparent"

[keys.normal]
X = "extend_line_above"
G = "goto_file_end"

[keys.normal.space]
q = ":buffer-close"

[editor]
soft-wrap.enable = true
bufferline = "multiple"
jump-label-alphabet = "tnseriaoplfuwydhc,x.q;z/"
end-of-line-diagnostics = "hint"
inline-diagnostics.cursor-line = "error"

[editor.cursor-shape]
insert = "bar"
