[shell.files]
"helix/config.toml" = "~/.config/helix/config.toml"
"fish/config.fish" = "~/.config/fish/config.fish"
"kitty/kitty.conf" = "~/.config/kitty/kitty.conf"
"git/.gitconfig" = "~/.gitconfig"
"paru/paru.conf" = "~/.config/paru/paru.conf"
