[shell.files]
"helix/config.toml" = "~/.config/helix/config.toml"
"helix/languages.toml" = "~/.config/helix/languages.toml"
"helix/gruvbox_transparent.toml" = "~/.config/helix/themes/gruvbox_transparent.toml"
"fish/config.fish" = "~/.config/fish/config.fish"
"kitty/kitty.conf" = "~/.config/kitty/kitty.conf"
"git/.gitconfig" = "~/.gitconfig"
"paru/paru.conf" = "~/.config/paru/paru.conf"

[hyprland.files]
"hyprland/hyprland.conf" = "~/.config/hypr/hyprland.conf"
"hyprland/hyprland-portals.conf" = "~/.config/xdg-desktop-portal/hyprland-portals.conf"
"hyprland/dunstrc" = "~/.config/dunst/dunstrc"
"hyprland/rofi.rasi" = "~/.config/rofi/config.rasi"
"hyprland/hyprlock.conf" = "~/.config/hypr/hyprlock.conf"
"hyprland/wpaperd.toml" = "~/.config/wpaperd/config.toml"
"hyprland/waybar" = "~/.config/waybar/config"
"hyprland/waybar.css" = "~/.config/waybar/style.css"
"hyprland/hyprshade.toml" = "~/.config/hypr/hyprshade.toml"
"hyprland/key_layout" = "~/.config/xkb/symbols/us-german"
# does not work because it needs to be root
# "hyprland/sddm.conf" = "/etc/sddm.conf.d/sddm.conf"
